url: http://conferenciaror.es
exclude: ["Gemfile","Gemfile.lock",".ruby-version",".ruby-gemset"]
style: compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
sass:
  style: compressed
  # sass_dir: _sass # default _sass
sponsor-levels:
  - name: ruby
    icon: heart
    sponsors: []
  - name: unobtainium
    sponsors: []
    icon: rocket
  - name: adamantium
    icon: diamond
    sponsors:
      - name: BeBanjo
        icon: bebanjo.svg
        url: http://bebanjo.com
      - name: FlyWire
        icon: flywire.png
        url: https://flywire.com
      - name: Besepa
        url: http://www.besepa.com
        icon: besepa.svg
      - name: Platform161
        url: http://platform161.com/
        icon: platform161.svg
      - name: ASPgems
        url: https://aspgems.com
        icon: aspgems.svg
  - name: supporter
    icon: thumbs-up
    sponsors:
      - name: ProRuby Team
        url: http://www.prorubyteam.com
      - name: RubyGarage
        url: https://rubygarage.org/
